module.exports = {
  CHAT_ROOM:"CHAT_ROOM",
  USER_CONNECTED:"USER_CONNECTED",
  MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
  MESSAGE_SENT:"MESSAGE_SENT",
  USER_DISCONNECTED:"USER_DISCONNECTED",
  TYPING:"TYPING",
  CONFIRM_USER:"CONFIRM_USER",
  LOGOUT:"LOGOUT",
  ROOM_WELCOME:"ROOM_WELCOME"

}